### ISSUE TITLE
Animating box-shadow property

### ISSUE THREAD

**Issue by pel-daniel** [jquery/jquery-color#108]
Hi, I would like to know if it's possible to animate the box-shadow property using a hook or by some other way.
I tried `jQuery.hook('boxShadow')` but it didn't work. 
The box-shadow property has more values aside from the color, e.g. `box-shadow: 3px 3px black`.

**Comment by raphamorim** [comment]
Which JQuery version you're using @pel-daniel ?

**Comment by pel-daniel** [comment]
I am using jquery 2.2.4 and jquery.color 2.1.2

**Comment by raphamorim** [comment]
`hook` method doesn't exist in that context,
You have to use `JQuery.Color.hook`.

**Comment by pel-daniel** [comment]
Thanks for your response.
I tried using `jQuery.Color.hook` and doesn't work either. I checked in the browser console (I am using chrome) and the method does exist.

I created a jsfiddle so you can see what I'm doing [https://jsfiddle.net/17tgjvju/3/](https://jsfiddle.net/17tgjvju/3/)

**Comment by mgol** [comment]
`box-shadow`'s value is not a color hence using `jQuery.Color.hook` won't help.

I'm afraid this might be out of scope of the project. We welcome any ideas how to integrate support but otherwise I'm going to close this as "Won't fix" for now.
