### ISSUE TITLE
Doesn't work on Safari 8.0.2 (Yosemite)

### ISSUE THREAD

**Issue by davidkhasikyan** [jquery/jquery-color#109]
Tried to use lightness function but it seems doesn't work on Safari ( Yosemite ).

Thanks.

**Comment by mgol** [comment]
Sorry for lack of response.

This plugin only supports browsers that jQuery 3.x supports which means only last two Safari versions are supported, currently 9 & 10. Therefore, bugs may exist in older versions.

If it doesn't work in newer versions for you, please provide a test case on https://jsfiddle.net or https://jsbin.com and we'll reopen.
