### ISSUE TITLE
JQuery dependency

### ISSUE THREAD

**Issue by CaballoCarpiano** [jquery/jquery-color#112]
The library uses the 'JQuery' package and causes conflict with other libraries that use the correct case package 'jquery'. Also I'm having a bad time implementing easeing (ease In), does this plugin support easing?

Thanks!

**Comment by mgol** [comment]
I don't see any `JQuery` mention in code; please elaborate on what version of the plugin you use and how are you getting it.

**Comment by alexdresko** [comment]
Here's what I think the OP is referring to. I'm seeing the same problem. 

```
npm install
npm WARN deprecated jQuery@1.7.4: This is deprecated. Please use 'jquery' (all lowercase).
registration-common@1.0.0 C:\code\stark\Registration\Custom\Stark RFID\DBC\Registration
`-- jquery-color@1.0.0
  `-- jQuery@1.7.4
```

**Comment by alexdresko** [comment]
Looks like it's fixed in the master branch, but it's a pre-release? 

The current package on npm has this:

```
  "dependencies": {
    "jQuery": "latest"
  },
```

...and that's causing major problems.

**Comment by alexdresko** [comment]
_Actually_ `npm install jquery-color --save` installs https://www.npmjs.com/package/jquery-color, I believe, which is not the same as this repo (even though they have the same name in package.json. 

Can you explain which package is definitive? I'm confused.

**Comment by leobalter** [comment]
we need to publish a new version now we've got the npm package name back.

cc @gnarf (who has the ownership, I believe)

**Comment by alexdresko** [comment]
In the meantime, I was able to `npm install https://github.com/jquery/jquery-color --save`

**Comment by mgol** [comment]
@gnarf it'd be good if you added more package owners so that we don't have to rely on you to release. :)

**Comment by leobalter** [comment]
It's my bad, @mgol. I've been working together with @gnarf as I requested their help. We'll have a meeting tomorrow morning and I'll try to get this fixed.

**Comment by gnarf** [comment]
@mgol @leobalter you both have owner on jquery-color npm package now

**Comment by mgol** [comment]
Thanks, @gnarf!

**Comment by gnarf** [comment]
To speak to this issue itself -- `jquery-color` wasn't ever published by the team on npm, someone else had done it, and so it took us a lot longer than we expected to regain ownership, and by the time the swap happened, I had lost the steam to push a new release :)  If @mgol or @leobalter can take care of publishing a new release, it will work so much better!

**Comment by gnarf** [comment]
See also #84 -- I believe this will be solved when this is done so I'm gonna close this one.
