### ISSUE TITLE
Can't animate color when style background color is set

### ISSUE THREAD

**Issue by daviddavo** [jquery/jquery-color#117]
This is a small code that I wrote. It works only the first time. When It sets the color the first time, it doesn't change it again. I think it's because when the `style='background-color: rgba( <color> )`  is set, the plugin can't change it again

```javascript
function onScroll(){
    if ( $( window ).scrollTop()*1.05 > $( window ).height() ){
      console.log("Tored");
      //$( "#navbar.fixed-top" ).addClass( "navbar-color" );
      $( "#navbar.fixed-top" ).animate({ backgroundColor: jQuery.Color( "rgba(162,14,14,1)" )}, "slow");
    }else{
      //$( "#navbar.fixed-top").removeClass( "navbar-color" );
      console.log("Toblank");
      $( "#navbar.fixed-top" ).animate({ backgroundColor: jQuery.Color( "rgba(0,0,0,0)" )}, "slow");
    }
  };
```

**Comment by mgol** [comment]
Thanks for the report. Could you provide a test case on [JSFiddle](https://jsfiddle.net/) or [JS Bin](https://jsbin.com/)? Thanks!

**Comment by daviddavo** [comment]
Yeah
https://jsfiddle.net/tk3b32pm/
When you press "To blank", I think that the div background-color should do a transition to rgba(0,0,0,0) color

**Comment by Dorifor** [comment]
I don't know why this isn't Closed yet, the only problem was that you didn't put # at line 5 `$("button2").click(function(e)`

**Comment by mgol** [comment]
Closing per comment https://github.com/jquery/jquery-color/issues/117#issuecomment-432370221.
