### ISSUE TITLE
please update npm source

### ISSUE THREAD

**Issue by Willworkgogogo** [jquery/jquery-color#124]
please please please update npm source!!！ thank u very much!

**Comment by mgol** [comment]
What do you mean by this report? Please elaborate.

We've recently released `jquery-color` `3.0.0-alpha.1` to npm, it's ready to test.

**Comment by mgol** [comment]
[jQuery Color 2.2.0](https://github.com/jquery/jquery-color/releases/tag/2.2.0) has been released, it's also published to npm.
