### ISSUE TITLE
import 'jquery-color' is no longer working

### ISSUE THREAD

**Issue by d-luk** [jquery/jquery-color#125]
I have been using this plugin in my project, but as it is not available at npm I added the repository url as a dependency in my package.json: 

`"dependencies: { "jquery-color": "https://github.com/jquery/jquery-color }`

And I import the plugin in my code with `import 'jquery-color';`.

But with the latest commits this is no longer working (> `69034583484c185b156ee8a3d120c8feea791e2d`). Webpack gives me this error: `Module not found: Error: Can't resolve 'jquery-color'`. 

Please either fix this problem or, preferably, publish the module on npm (and add it to the readme)

**Comment by mgol** [comment]
Thanks for the report.

Installing from a repo won't work as `main` refers to a file generated by the build process and not present in the repo.

`jquery-color` is published to npm, though. `3.0.0-alpha.1` is ready to test, we're awaiting feedback to make sure the final release works before actually pushing it; please test & report issues!

To install:
```
npm install jquery-color@beta
```

**Comment by mgol** [comment]
The package is updated, we just haven't released a stable version (I posted above how to install the experimental version). The more people test it the more likely we'll fix issues that might exist and release a stable `3.0.0` to npm.

README on the package npm page is the README of the latest version that was published as `latest` so it doesn't take alphas or betas into account.

**Comment by sativ01** [comment]
Hi,
I'm having the same issue. 
But I can't use unstable libraries in the project.
What could I do to make v2.1.2 work from npm?

Thanks!

**Comment by mgol** [comment]
[jQuery Color 2.2.0](https://github.com/jquery/jquery-color/releases/tag/2.2.0) has been released, it's also published to npm.
