### ISSUE TITLE
Update npm package jquery-color

### ISSUE THREAD

**Issue by jfoclpf** [jquery/jquery-color#128]
Could you kindly update your [npm package `jquery-color`](https://www.npmjs.com/package/jquery-color)?

It still mentions `v1.0.0` and it has a single npm dependency for an old version of jquery, namely [jquery v1.7.4](https://www.npmjs.com/package/jQuery) which is deprecated.

Any reason why jquery-color doesn't work with the lastest version of jquery?

I suppose you just need to do 

```
npm i jquery@">=1.11.0"
npm version <new version>
npm publish
```

Furthermore in said npm package the link to github gives 404 page not found, when it should redirect here.

**Comment by jfoclpf** [comment]
Not so much npm friendly :) 
I tried though
`npm install https://github.com/jquery/jquery-color` but the target installation folder has only these files

```
$ ls node_modules/jquery-color/
AUTHORS.txt  LICENSE.txt  package.json  README.md
```

**Comment by mgol** [comment]
We will publish a final version of the package on npm when we're ready to release jQuery Color 3.0.0.

For now, you can install a beta:
```
npm install jquery-color@beta
```
Please report issues with this package if there are any that are not already reported.

**Comment by mgol** [comment]
Here you can see blockers for the 3.0.0 release: https://github.com/jquery/jquery-color/milestone/1

**Comment by mgol** [comment]
Yes, as far as I know it should update the package to the final version once it's released.

**Comment by oshihirii** [comment]
Is this npm package the 'official' one?

The package's Github page is listed as:

https://github.com/znetstar/jquery-color

which returns a 404 error at the moment.  

Also, can anyone provide simple install instructions for this package?

Is it just:

    npm install jquery-color@beta

and then in your js file:

    import jquery-color from 'jquery-color'; 

    $(document).on("click", ".click_me", function() {  
    
        $(this).animate({
		backgroundColor: "#abcdef"
	}, 1500 );    
    
    });  

I was reading the front page of this repo (https://github.com/jquery/jquery-color) and it said grunt was required and i don't use grunt so was a bit confused as to how to install it.

Thank You.

**Comment by mgol** [comment]
@oshihirii See https://github.com/jquery/jquery-color/issues/128#issuecomment-431969394. The current stable version of the package was not published by us, the next stable version will be (once we get to it).

**Comment by mgol** [comment]
[jQuery Color 2.2.0](https://github.com/jquery/jquery-color/releases/tag/2.2.0) has been released, it's also published to npm.
