### ISSUE TITLE
Support for 8-digit hex colors

### ISSUE THREAD

**Issue by FeBe95** [jquery/jquery-color#129]
Are there any plans to implement 8-digit hex colors (e.g. "#ffaa0055")?
There is PR #126 from early 2018 that is still open. Could you merge this PR?

**Comment by davloperez** [comment]
It would be great to have this PR merged. It works like a charm. Please...

**Comment by mgol** [comment]
Released in [jQuery Color 2.2.0](https://github.com/jquery/jquery-color/releases/tag/2.2.0).

**Comment by mgol** [comment]
Thanks for contributing!
