### ISSUE TITLE
rgb/hsl transformation inaccurate

### ISSUE THREAD

**Issue by rodneyrehm** [jquery/jquery-color#50]
Hey there,

``` javascript
jQuery.Color(jQuery.Color("rgb(250, 234, 215)").toHslaString()).toRgbaString()
// "rgb(250,234,214)"
```

so converting an RGB to HSL and back might not yield the same color. Is this a problem with your implementation or with HSL per se. I couldn't find any pointer on floating point specificity in [CSS Color Module: HSL](http://www.w3.org/TR/css3-color/#hsl-color) but assume floats are accepted as well, as they are hinted (`float range 0.0% - 100.0%`) in [Example VII](http://www.w3.org/TR/css3-color/#rgba-color).

Not yet sure if this a bug or not :/

**Comment by vanderlee** [comment]
It's a problem with HSL.

Both appear to have 3 channels of 8 bits precission each; 24 bits in total.
For RGB, this truely means 2^24 unique colors.

But if you play around with a colorpicker in HSL (or HSV/HSB) mode you'll see some particular effects:

1. If L is zero, the color will always be black, regardless of the values of H or S.
2. If S is zero, the color will always be a grayscale, regardless of the value of H.

This means that for certain of those combinations of H, S and L, the colors are identical. This means that for HSL, you have less than 2^24 colors.

It should be obvious now, that there is a loss of information when converting from RGB to HSL and back to RGB, so there is a chance the color might change a small bit.

This is not just an implementation issue; it's a result of how HSL color space works. If you use floats, you'd have the same problem (though less noticable).

**Comment by mgol** [comment]
Closing per @vanderlee's comment.

**Comment by chevex** [comment]
lol
