### ISSUE TITLE
Setting alpha via an object doesn't work

### ISSUE THREAD

**Issue by derekcicerone** [jquery/jquery-color#58]
$.Color({red: 10, green: 10, blue: 10, alpha: 0.5}) results in a color with alpha set to 1.

The bug appears to be at line 276 in this section:
          // everything defined but alpha?
          if ( inst[ cache ] && jQuery.inArray( null, inst[ cache ].slice( 0, 3 ) ) < 0 ) {
            // use the default of 1
            inst[ cache ][ 3 ] = 1;
            if ( space.from ) {
              inst._rgba = space.from( inst[ cache ] );
            }
          }

It seems to just clear out the alpha every time.

**Comment by rvaidya** [comment]
This still seems to be an issue, 2 years later.

The workaround is to do $.Color({red: 10, green: 10, blue: 10, alpha: 0.5}).alpha(0.5), but then what's the point of having it in the constructor in the first place?

Also affects HSLA.

**Comment by mgol** [comment]
jQuery Color `3.0.0-alpha.1` has been published to npm under the tag `beta`. It's also on the CDN: https://code.jquery.com/color/3.0.0-alpha.1/jquery.color.js.

Please test and report any issues before we release the final!

**Comment by mgol** [comment]
Released in [jQuery Color 2.2.0](https://github.com/jquery/jquery-color/releases/tag/2.2.0).
