### ISSUE TITLE
borderColor test fails with newer QUnit

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/jquery-color#69]
The borderColor animation test runs assertions even after the test has finished. This happens because the `step` callback is invoked for every property, even though the `.stop()` is called for the first property. The test seems strange as is, so I'm not sure how to fix it because I'm not sure it's really testing something it should.

**Comment by raphamorim** [comment]
Ref: QUnit update to 1.22.0 https://github.com/jquery/jquery-color/commit/c0e3bfbdc8e7660ca2ddc9886df42469cdef4239

**Comment by raphamorim** [comment]
@mgol @gnarf I think we can close this issue :octocat:

**Comment by mgol** [comment]
This doesn't seem relevant anymore.
