### ISSUE TITLE
Module Loader Friendly Versions

### ISSUE THREAD

**Issue by gnarf** [jquery/jquery-color#77]
See #73 - basically jQuery Color should be able to work inside of amd/commonjs style module systems.

**Comment by ZebraFlesh** [comment]
This would be great. As it stands now, it's a great package, but a real pain to use from an ES6 environment (such as ember-cli).

**Comment by niallobrien** [comment]
:+1:

**Comment by niallobrien** [comment]
Right now, I'd like to be able to require jquery-color.
