### ISSUE TITLE
Browser Support?

### ISSUE THREAD

**Issue by nekkon** [jquery/jquery-color#82]
Could you please tell me browser support for this plugin?

**Comment by scottgonzalez** [comment]
This plugin doesn't really do anything with the DOM, so browser support will be based on the version of jQuery Core that you're using.

**Comment by mzgol** [comment]
Seems that we should add such info to README, it might not be obvious to people that didn't work on the code.

@nekkon This plugin is now tested in all browsers supported by jQuery 1.x: http://swarm.jquery.org/job/1746. So it definitely works on those.

**Comment by raphamorim** [comment]
I've added this info into Readme, what do you think @mgol, @scottgonzalez?  #86
