### ISSUE TITLE
update npm package

### ISSUE THREAD

**Issue by Mithgol** [jquery/jquery-color#84]
I've noticed that npm [thinks](https://www.npmjs.com/package/jquery-color) that `jquery-color` package is still v1.0.0 and that it depends on `jQuery` package (contrary to what `package.json` currently says).

Can you `npm publish` newer version(s) of the package?

**Comment by mzgol** [comment]
The `jquery-color` package is not maintained by us, you can see in the package metadata that it points to https://github.com/znetstar/jquery-color that doesn't exist anymore.

We'd have to take the ownership of the package first. @dmethvin & @scottgonzalez, do you think we'd like to do it?

BTW, @gnarf, the latest version has been released a long time ago, should we tag a new one?

**Comment by scottgonzalez** [comment]
I contacted the owner of the module.

**Comment by gnarf** [comment]
We might want to get the build chain up to date and make sure everything
still works in color.

I'm really to busy with my parents estate to do anything about it anytime
soon, would someone else like to maintain this?

**Comment by mzgol** [comment]
I won't have time before January-February, a lot of work-related changes going on & the upcoming Core releases are enough. If no one steps up I might try later.

**Comment by mgol** [comment]
@leobalter We only control the npm package, not the Bower one, do we still want to use [jquery-release](https://github.com/jquery/jquery-release) for publishing or not?

Note that if we don't use jquery-release we have to be careful to define a proper `.npmignore` or the `files` array in `package.json` to not publish IDE directories like `.idea` or temporary files under `dist`.

**Comment by leobalter** [comment]
> @leobalter We only control the npm package, not the Bower one, do we still want to use jquery-release for publishing or not?

I honestly don't care about publishing it to bower. We should be fine with npm only.

> Note that if we don't use jquery-release we have to be careful to define a proper .npmignore or the files array in package.json to not publish IDE directories like .idea or temporary files under dist.

Unless we want to use the CDN for publishing static files, we should also skip using jquery-release, IMHO.

+1 to define .npmignore properly.

**Comment by mgol** [comment]
I submitted a PR with `.npmignore` & other updates: #114. Once that lands, we could publish a new version.

There are [some issues to fix](https://github.com/jquery/jquery-color/issues) but we can deal with them after 3.0.0 as most of them don't seem to require breaking changes.

**Comment by raphamorim** [comment]
Closed on #114 
Thanks @mgol 

If have other issue about it we can reopen this issue :)

**Comment by mgol** [comment]
We still need to publish a new release to npm (which this issue is about) so I'll reopen for now.

We still need to somehow ensure `npm publish` will be run directly after building files to not have something obsolete in `dist/` published. We could use the new npm `prepare` script if we ensure we're publishing with npm 4 and not sth older.

I'll try that on a branch and publish to my scoped package to make sure we're fine before doing it here.

**Comment by jcairney** [comment]
Hi,
Looking forward to this update to npm.  Please finish.  As an example of why, a seller called Orange is selling a very popular website template on wrapbootstrap.com called Smart Admin which is using jquery-color.  Many people are unwittingly paying for and inheriting code that is depending on jquery-color which is using a dependency of "jQuery" 1.7.4 which conflicts with the requirements of most other modules in the template using "jquery" 2.2.4 or above, causing huge headaches.

**Comment by jimmymain** [comment]
let's get this done, anything I can do to help... I lost a few hours of my life to znetstar that I will never get back... :-)

**Comment by mgol** [comment]
@leobalter 
> Unless we want to use the CDN for publishing static files, we should also skip using jquery-release, IMHO.

We publish to our own CDN: https://code.jquery.com/color/. Perhaps we should continue to do that in that case. Maybe we need [jquery-release](https://github.com/jquery/jquery-release/) in the end, otherwise we have to follow those steps by ourselves.

**Comment by mgol** [comment]
I've submitted a housekeeping PR I'd like to land shortly, PTAL: https://github.com/jquery/jquery-color/pull/120.

**Comment by mgol** [comment]
jQuery Color `3.0.0-alpha.1` has been published to npm under the tag `beta`. It's also on the CDN: https://code.jquery.com/color/3.0.0-alpha.1/jquery.color.js.

Please test and report any issues before we release the final!

**Comment by mgol** [comment]
FWIW, I've used `jquery-release` to release the version.

**Comment by mgol** [comment]
@ntwb No, it's published as `jquery-color`. You can see your link is a 404.

**Comment by ntwb** [comment]
Right, I thought that because https://www.npmjs.com/package/jquery-color still shows the 1.0.0 release from znetstar /shrug

Cheers,

Stephen Edgar
________________________________

**Comment by mgol** [comment]
@ntwb It's because I've only released a pre-release (`3.0.0-alpha.1`) so it's tagged as `beta`, not `latest`. It will change once we release a final `3.0.0`.

In the meantime, please test the alpha, that'll help to release the final sooner.

**Comment by jfoclpf** [comment]
just to confirm: is the correspondent npm package `jquery-color` ?
https://www.npmjs.com/package/jquery-color
just because the github link of said npm package returns a 404 page not found, and it should return here

**Comment by jfoclpf** [comment]
could you also insert in said package, besides a `jquery.color.js` a `jquery.color.min.js`?

**Comment by mgol** [comment]
@jfoclpf the package is in preview. If you want to try it, you need to invoke:
```
npm install jquery-color@beta
```

I encourage you to test it & submit issues if you discover any. The more people try it, the more likely we'll release a final in a predictable future.

**Comment by jfoclpf** [comment]
I tried and it seems great. Though in your `package.json` I think you need a dependency to `jquery`, since `jquery-color`, I suppose, doesn't work without `jquery`

I see this in your `package.json`

```
  "dependencies": {},
  "deprecated": false,
  "description": "jQuery plugin for color manipulation and animation support.",
```

That is, `dependencies` is an empty object. You just filled in `devDependencies`, and no `jquery` within it.

For adding a dependency you just need to

```
npm i jquery@">=1.11.0"
npm version <new version>
npm publish
```

I don't think you need to publish as beta, if jquery-color is tested to work fine.

**Comment by mgol** [comment]
jQuery is not a dependency but a peerDependency of jQuery Color. This is
because each jQuery plugin should use the same jQuery instance, not its
own. peerDependencies are not enforced by npm to avoid dependency hell
(older npm used to enforce that and even auto-install peerDeps) but you
should see a warning in the console if you don’t install jQuery.
-- 
Michał Gołębiowski-Owczarek

**Comment by mgol** [comment]
[jQuery Color 2.2.0](https://github.com/jquery/jquery-color/releases/tag/2.2.0) has been released, it's also published to npm.
