### ISSUE TITLE
Reconsolidate with Wikimedia fork

### ISSUE THREAD

**Issue by Krinkle** [jquery/jquery-color#85]
I forked this plugin in 2011 within the wikimedia/mediawiki repository (https://github.com/wikimedia/mediawiki/commit/83a7822df7b).

Current files:
- [src/jquery.colorUtil.js](https://github.com/wikimedia/mediawiki/blob/bc78528179/resources/src/jquery/jquery.colorUtil.js)
- [src/jquery.color.js](https://github.com/wikimedia/mediawiki/blob/bc78528179/resources/src/jquery/jquery.color.js)
- [test/qunit/jquery.color.test.js](https://github.com/wikimedia/mediawiki/blob/bc78528179/tests/qunit/suites/resources/jquery/jquery.color.test.js)
- [test/qunit/jquery.colorUtil.test.js](https://github.com/wikimedia/mediawiki/blob/bc78528179/tests/qunit/suites/resources/jquery/jquery.colorUtil.test.js)

I would love to reconsolidate with upstream.

**Comment by Krinkle** [comment]
The fork also has fairly elaborate QUnit tests (using latest version of QUnit) which may be useful. Ping issue #69.

**Comment by scottgonzalez** [comment]
The main repo has added a ton of functionality since then. Is there anything in the Wikimedia fork that doesn't already exist at this point?

**Comment by leobalter** [comment]
@raphamorim do you wanna check this in?

**Comment by raphamorim** [comment]
Ok, leave it to me.

**Comment by raphamorim** [comment]
@leobalter @Krinkle I checked the differences, but the jquery-color evolved **a lot** since 2011. Which results a huge change in main repo.

I believe that the best way would be to specify features they would like to be added.

**Comment by leobalter** [comment]
We can do this at least from the tests. This way we guarantee a great use
case (Wikimedia).
It's worth the complexity. :)

**Comment by scottgonzalez** [comment]
This thread has stalled. Let's open a separate issue for each individual feature, if there still are any.
