### ISSUE TITLE
Drop IE 6 "fake alpha" support?

### ISSUE THREAD

**Issue by gnarf** [jquery/jquery-color#89]
I think it's time, anyone agree?

cc @scottgonzalez for the UI perspective

**Comment by scottgonzalez** [comment]
Hah, we haven't supported IE6 in UI for quite a while.

**Comment by mgol** [comment]
I agree, let's do it. Especially that IE6 support is problematic from BrowserStack's side, they're keeping one machine constantly running just for us because a regularly spawned one was crashing etc. It'd be nice of us for them to stop using those machines, especially with Core dropping the 1.x jQuery line.

**Comment by mgol** [comment]
Should we align the set of officially supported & tested browsers with what jQuery 3 will support? That would be cutting support for IE 6-8, Android 2.3, Safari 5.1-7.0 & Opera 12.1x.

**Comment by mgol** [comment]
Is the fake alpha IE6-only, though? [The support test](https://github.com/jquery/jquery-color/blob/a64bdaec0124f81d278ad53ba74bb106b297572c/jquery.color.js#L146-L147) will be passed by IE9+ only and [that's what's checked](https://github.com/jquery/jquery-color/blob/a64bdaec0124f81d278ad53ba74bb106b297572c/jquery.color.js#L594) when deciding whether to blend.

**Comment by leobalter** [comment]
> Should we align the set of officially supported & tested browsers with what jQuery 3 will support?

I agree with it, and it doesn't hurt if we need to release a new major version as well to flag the support drop.

**Comment by mgol** [comment]
@leobalter Who's maintaining this project now? Should we ask someone else for an opinion?

**Comment by leobalter** [comment]
That's supposed to be me. At least I volunteered on this. @gnarf is the
best person to consult, I believe.

**Comment by mgol** [comment]
OK, great. :) I'm assigning it to myself then.

**Comment by mgol** [comment]
PR: #104.

Please review.
