### ISSUE TITLE
replace bower dependencies with npm packages

### ISSUE THREAD

**Issue by leobalter** [jquery/jquery-color#93]
Can we fetch all dependencies from npm packages? I guess so.

**Comment by leobalter** [comment]
that might kill the npm warning for the missing jQuery peer-dependency.

**Comment by raphamorim** [comment]
Leave it to me :+1:

**Comment by mgol** [comment]
I think we determined in #107 that we're not going to fix it (at least for the time being) because npm doesn't support (and doesn't plan to support) package aliases which we rely on.
