### ISSUE TITLE
Update QUnit version and syntax

### ISSUE THREAD

**Issue by leobalter** [jquery/jquery-color#94]
Update QUnit to its newest version and update the tests to remove deprecated syntax/API.

**Comment by raphamorim** [comment]
@leobalter Do you think better to wait the release of QUnit 2.0 to implement this PR?

**Comment by leobalter** [comment]
it's not necessary to wait. QUnit 2.0 will just remove deprecated api/syntax. The latest QUnit 1.x release non-deprecated api will work on QUnit 2 without any magic.

**Comment by raphamorim** [comment]
I see, leave it to me then :)

**Comment by Krinkle** [comment]
See #85.
