### ISSUE TITLE
Update npm packages

### ISSUE THREAD

**Issue by leobalter** [jquery/jquery-color#95]
Keeping them locked

**Comment by raphamorim** [comment]
Ref: https://github.com/jquery/jquery-color/pull/103

**Comment by Mithgol** [comment]
#103 is stalled for three months, npm-published [`jquery-color`](https://www.npmjs.com/package/jquery-color) is four years old.

**Comment by leobalter** [comment]
my bad. Thanks for the reminder. I'll try to do it this week.

**Comment by Mithgol** [comment]
This is a ≈monthly reminder.

#103 is stalled for four months, npm-published [`jquery-color`](https://www.npmjs.com/package/jquery-color) is five years old.

**Comment by leobalter** [comment]
It's merged now, thanks for the reminder.

**Comment by Mithgol** [comment]
Okay, #103 is merged, very good.

However, npm-published [`jquery-color`](https://www.npmjs.com/package/jquery-color) still seems five years old.
